# Generated by Django 2.2 on 2023-11-26 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account')], max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('cash_and_equivalents', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('property_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('other_assets', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('short_term_loans', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('accrued_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('long_term_debt', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('other_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('common_stock', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=112)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSS_number', models.CharField(blank=True, max_length=60, null=True)),
                ('edate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ecnicverification', models.CharField(blank=True, max_length=40, null=True)),
                ('edesignation', models.CharField(blank=True, max_length=40, null=True)),
                ('ename', models.CharField(blank=True, max_length=40, null=True)),
                ('efathername', models.CharField(blank=True, max_length=40, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('econtact', models.CharField(blank=True, max_length=40, null=True)),
                ('eexguard', models.CharField(blank=True, max_length=40, null=True)),
                ('ecategory', models.CharField(blank=True, max_length=40, null=True)),
                ('ecnicno', models.CharField(blank=True, max_length=40, null=True)),
                ('ecnicexpirydate', models.DateField(blank=True, null=True)),
                ('edateofbirth', models.DateField(blank=True, null=True)),
                ('epresentaddress', models.CharField(blank=True, max_length=60, null=True)),
                ('epermenantaddress', models.CharField(blank=True, max_length=60, null=True)),
                ('eserviceno', models.CharField(blank=True, max_length=40, null=True)),
                ('weapondate', models.DateField(blank=True, null=True)),
                ('weapono', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('weaponname', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('uniformissuedate', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('weapon_picture', models.ImageField(blank=True, null=True, upload_to='weapon_images/')),
                ('employee_card_image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniformItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UniformSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('computerized_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('weapon_number', models.CharField(blank=True, max_length=50, null=True)),
                ('make_weapons', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('weapon_purchase_from', models.CharField(blank=True, max_length=100, null=True)),
                ('weapon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('weapon_serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ammu', models.CharField(blank=True, max_length=50, null=True)),
                ('guard_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guard_sign', models.ImageField(blank=True, null=True, upload_to='guard_signs/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniformSlipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.UniformItem')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.UniformSlip')),
            ],
        ),
        migrations.AddField(
            model_name='uniformslip',
            name='items',
            field=models.ManyToManyField(through='meerapp.UniformSlipItem', to='meerapp.UniformItem'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_description', models.CharField(default='Some Default Value', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='meerapp.Account')),
                ('debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='meerapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('guards_required', models.PositiveIntegerField(default=0)),
                ('assigned_guards', models.ManyToManyField(blank=True, to='meerapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_name', models.CharField(blank=True, default='no', max_length=200, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meerapp.Location'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('overtime_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.Employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meerapp.Location')),
                ('overtime_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_attendances', to='meerapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('full_days', models.PositiveIntegerField()),
                ('half_days', models.PositiveIntegerField()),
                ('overtime_full_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_half_day_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.Employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
