# Generated by Django 4.2.7 on 2023-11-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0003_remove_account_accounts_payable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash', 'Cash')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='post_dated_cheque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='head_of_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meerapp.headofaccount'),
        ),
    ]
