# Generated by Django 4.2.7 on 2023-11-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0004_headofaccount_remove_transaction_trans_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='meerapp.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='meerapp.account'),
        ),
    ]
