# Generated by Django 4.2.7 on 2023-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0005_alter_transaction_credit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
