# Generated by Django 4.2.7 on 2023-12-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0007_remove_transaction_executed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniformIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='uniformslipitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='uniformslipitem',
            name='slip',
        ),
        migrations.RemoveField(
            model_name='uniformitem',
            name='name',
        ),
        migrations.AddField(
            model_name='uniformitem',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uniformitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UniformSlip',
        ),
        migrations.DeleteModel(
            name='UniformSlipItem',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='uniform_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.uniformissue'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='uniform_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.uniformitem'),
        ),
        migrations.AddField(
            model_name='uniformitem',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meerapp.uniform'),
        ),
    ]
