# Generated by Django 4.2.7 on 2023-12-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0008_lineitem_uniform_uniformissue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformissue',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='uniformitem',
            name='uniform',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Uniform',
        ),
        migrations.DeleteModel(
            name='UniformIssue',
        ),
        migrations.DeleteModel(
            name='UniformItem',
        ),
    ]
