# Generated by Django 4.2.7 on 2023-12-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0009_remove_uniformissue_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('uniform_issue_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UniformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerapp.uniformassignment')),
            ],
        ),
    ]
