# Generated by Django 4.2.7 on 2023-12-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0010_uniformassignment_uniformitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformitem',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='UniformAssignment',
        ),
        migrations.DeleteModel(
            name='UniformItem',
        ),
    ]
