# Generated by Django 4.2.7 on 2023-12-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerapp', '0013_rename_employee_lineitem_uniform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='total_amount',
        ),
    ]
